name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Tag Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: my-docker-app:latest,bahamelki/my-docker-app:latest  # Tag for both local and Docker Hub
          load: true  # Make image available locally

      - name: Run Tests
        run: docker run --rm my-docker-app:latest ./run-tests.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true  # Only push the image (no rebuild)
          tags: bahamelki/my-docker-app:latest